var products = [

// Tabloids
	{
		title: 'National Enquirer',
		image: 'assets/images/national_enquirer.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'National Examiner',
		image: 'assets/images/national_examiner.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'Globe',
		image: 'assets/images/globe.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'Star',
		image: 'assets/images/star.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'Country Weekly',
		image: 'assets/images/country_weekly.jpg',
		genre: '01 - Tabloid',
		minorder: '3',
		frequency: 'W',
	},

// News & Entertainment
	{
		title: 'In Touch Weekly',
		image: 'assets/images/in_touch_weekly.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'Life & Style',
		image: 'assets/images/life_style.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'OK Magazine',
		image: 'assets/images/ok_magazine.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'People Weekly',
		image: 'assets/images/people_weekly.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
	},
	{
		title: 'Soap Opera Digest',
		image: 'assets/images/soap_opera_digest.jpg',
		genre: '02 - News & Entertainment',
		minorder: '2',
		frequency: 'W',
	},
	{
		title: 'Time',
		image: 'assets/images/time.jpg',
		genre: '02 - News & Entertainment',
		minorder: '2',
		frequency: 'W',
	},
	{
		title: 'US Weekly',
		image: 'assets/images/us_weekly.jpg',
		genre: '02 - News & Entertainment',
		minorder: '3',
		frequency: 'W',
	},

// Sports & Health
	{
		title: 'Boating',
		image: 'assets/images/boating.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Field & Stream',
		image: 'assets/images/field_stream.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Fitness Rx for Men',
		image: 'assets/images/fitness_rx_men.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Fitness Rx for Women',
		image: 'assets/images/fitness_rx_women.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Flex',
		image: 'assets/images/flex.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Fly Rod & Reel',
		image: 'assets/images/fly_rod_reel.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Golf Digest',
		image: 'assets/images/golf_digest.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Hunting',
		image: 'assets/images/hunting.jpg',
		genre: '03 - Sports & Health',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'In-Fisherman',
		image: 'assets/images/in_fisherman.jpg',
		genre: '03 - Sports & Health',
		minorder: '3',
		frequency: 'BM',
	},
	{
		title: 'Mens Fitness',
		image: 'assets/images/mens_fitness.jpg',
		genre: '03 - Sports & Health',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Mens Health',
		image: 'assets/images/mens_health.jpg',
		genre: '03 - Sports & Health',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Muscle & Fitness',
		image: 'assets/images/muscle_fitness.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Natural Health',
		image: 'assets/images/natural_health.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Organic Life',
		image: 'assets/images/no-pic.jpg',
		genre: '03 - Sports & Health',
		minorder: '5',
		frequency: 'BM',
	},
	{
		title: 'Outdoor Life',
		image: 'assets/images/outdoor_life.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Prevention',
		image: 'assets/images/prevention.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Runners World',
		image: 'assets/images/runners_world.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Shape',
		image: 'assets/images/shape.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Sport Fishing',
		image: 'assets/images/sport_fishing.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Sports Illustrated',
		image: 'assets/images/sports_illustrated.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'W',
	},
	{
		title: 'Weight Watchers',
		image: 'assets/images/weight_watchers.jpg',
		genre: '03 - Sports & Health',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Womens Running',
		image: 'assets/images/no-pic.jpg',
		genre: '03 - Sports & Health',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'WWE Smackdown',
//		image: 'assets/images/wwe_smackdown.jpg',
//		genre: '03 - Sports & Health',
//		minorder: '*',
//		frequency: '*',
//	},

// Men & Fashion
	{
		title: 'Details',
		image: 'assets/images/details.jpg',
		genre: '04 - Men & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'GQ',
		image: 'assets/images/gq.jpg',
		genre: '04 - Men & Fashion',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Maxim',
//		image: 'assets/images/maxim.jpg',
//		genre: '04 - Men & Fashion',
//		minorder: '*',
//		frequency: '*',
//	},

// Auto & Racing
	{
		title: 'American Iron',
		image: 'assets/images/american_iron.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Auto Round-Up',
		image: 'assets/images/auto_round_up.jpg',
		genre: '05 - Auto & Racing',
		minorder: '3',
		frequency: 'BW',
	},
	{
		title: 'Auto / Truck Roundup',
		image: 'assets/images/auto_truck_roundup.jpg',
		genre: '05 - Auto & Racing',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Car & Driver',
		image: 'assets/images/car_driver.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Car Craft',
		image: 'assets/images/car_craft.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Cycle World',
		image: 'assets/images/cycle_world.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Easy Rider',
		image: 'assets/images/easy_rider.jpg',
		genre: '05 - Auto & Racing',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Four Wheeler',
		image: 'assets/images/four_wheeler.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Hot Rod',
		image: 'assets/images/hot_rod.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Motor Trend',
		image: 'assets/images/motor_trend.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Off Road',
		image: 'assets/images/off_road.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Popular Hotrodding',
//		image: 'assets/images/popular_hotrodding.jpg',
//		genre: '05 - Auto & Racing',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Road & Track',
		image: 'assets/images/road_track.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Motorcycle Baggers',
		image: 'assets/images/motorcycle_bagger.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Truck Roundup',
		image: 'assets/images/truck_roundup.jpg',
		genre: '05 - Auto & Racing',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Truckin',
		image: 'assets/images/truckin.jpg',
		genre: '05 - Auto & Racing',
		minorder: '2',
		frequency: 'M',
	},

// Women & Fashion
	{
		title: 'Allure',
		image: 'assets/images/allure.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Cosmopolitan',
		image: 'assets/images/cosmopolitan.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Elle',
		image: 'assets/images/elle.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Family Circle',
		image: 'assets/images/family_circle.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'First For Women',
		image: 'assets/images/first_for_women.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'BW',
	},
	{
		title: 'Glamour',
		image: 'assets/images/glamour.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Good Housekeeping',
		image: 'assets/images/good_housekeeping.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Harpers Bazaar',
		image: 'assets/images/harpers_bazaar.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'In Style',
		image: 'assets/images/in_style.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Ladies Home Journal',
//		image: 'assets/images/ladies_home_journal.jpg',
//		genre: '06 - Women & Fashion',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Marie Claire',
		image: 'assets/images/marie_claire.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Oprah',
		image: 'assets/images/oprah.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Redbook',
		image: 'assets/images/redbook.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Self',
		image: 'assets/images/self.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Vanity Fair',
		image: 'assets/images/vanity_fair.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Vogue',
		image: 'assets/images/vogue.jpg',
		genre: '06 - Women & Fashion',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Womans Day',
		image: 'assets/images/womans_day.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Womans World',
		image: 'assets/images/womans_world.jpg',
		genre: '06 - Women & Fashion',
		minorder: '3',
		frequency: 'W',
	},

// Business
	{
		title: 'Entrepreneur',
		image: 'assets/images/entrepreneur.jpg',
		genre: '07 - Business',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Forbes',
		image: 'assets/images/forbes.jpg',
		genre: '07 - Business',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Home Business',
		image: 'assets/images/home_business.jpg',
		genre: '07 - Business',
		minorder: '3',
		frequency: 'BM',
	},

// Children
	{
		title: 'Highlights For Children',
		image: 'assets/images/highlights_for_children.jpg',
		genre: '08 - Children',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Pre-K to Grade 1 Learning Fun',
		image: 'assets/images/no-pic.jpg',
		genre: '08 - Children',
		minorder: '3',
		frequency: 'M',
	},

// Computer
	{
		title: 'Wired',
		image: 'assets/images/wired.jpg',
		genre: '09 - Computer',
		minorder: '*',
		frequency: '*',
	},
	{
		title: 'X-Box',
		image: 'assets/images/xbox.jpg',
		genre: '09 - Computer',
		minorder: '*',
		frequency: '*',
	},

// Music
	{
		title: 'Rolling Stone',
		image: 'assets/images/rolling_stone.jpg',
		genre: '10 - Music',
		minorder: '3',
		frequency: 'M',
	},

// Teen
	{
		title: 'J-14',
		image: 'assets/images/j14.jpg',
		genre: '11 - Teen',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'M-Music, Movies More',
		image: 'assets/images/m_music_movies_more.jpg',
		genre: '11 - Teen',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Seventeen',
		image: 'assets/images/seventeen.jpg',
		genre: '11 - Teen',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Teen Vogue',
		image: 'assets/images/teen_vogue.jpg',
		genre: '11 - Teen',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Twist',
		image: 'assets/images/twist.jpg',
		genre: '11 - Teen',
		minorder: '2',
		frequency: 'M',
	},

// Puzzles & Crosswords
	{
		title: 'Celebrity Word Seek',
		image: 'assets/images/no-pic.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Chicken Soup for the Soul',
		image: 'assets/images/chicken_soup_for_the_soul.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Circle a Word',
		image: 'assets/images/circle_a_word.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Circle Circle',
		image: 'assets/images/circle_circle.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Dell Horoscope',
//		image: 'assets/images/dell_horoscope.jpg',
//		genre: '12 - Puzzles & Crosswords',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Easy Crosswords',
		image: 'assets/images/easy_crosswords.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Easy Sudoku',
		image: 'assets/images/easy_sudoku.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Family Variety Puzzle',
		image: 'assets/images/no-pic.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Games / World of Puzzles',
		image: 'assets/images/games.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '*',
		frequency: '*',
	},
	{
		title: 'Jumble',
		image: 'assets/images/no-pic.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Logic Lovers Puzzles',
		image: 'assets/images/logic_lovers_puzzels.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'National Observer',
		image: 'assets/images/national_observer.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Superb Word Find',
		image: 'assets/images/superb_word_find.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'USA Crosswords',
		image: 'assets/images/usa_crosswords.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Variety Word Find',
		image: 'assets/images/variety_word_find.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Wheel of Fortune Seek',
		image: 'assets/images/wheel_fortune_seek.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Games / World of Puzzles',
		image: 'assets/images/world_of_puzzles.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'World of Sudoku',
		image: 'assets/images/world_of_sudoku.jpg',
		genre: '12 - Puzzles & Crosswords',
		minorder: '2',
		frequency: 'M',
	},

// Adult Sophisticates
	{
		title: 'Beaver Hunt',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Cheri',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Club',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
//	{
//		title: 'Club Confidential',
//		image: 'assets/images/xxx.jpg',
//		genre: '13 - Adult Sophisticates',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Club International',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Club Spec.',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Erotic Film Guide',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Fox',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Gallery',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Girls of Penthouse',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'High Society',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Hustler / Best of Hustler',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: 'M',
	},
	{
		title: 'Hustler Barely Legal',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: 'M',
	},
	{
		title: 'Hustler Comix',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: '2x/A',
	},
	{
		title: 'Hustler Fantasies',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: 'M',
	},
	{
		title: 'Hustlers Lingerie',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: 'M',
	},
	{
		title: 'Hustler Taboo',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '8',
		frequency: 'M',
	},
	{
		title: 'Lollypops',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Nasty Housewives',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Penthouse',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Penthouse Forum',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Penthouse Letters',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Playboy',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Playboy Calendars',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '5',
		frequency: 'A',
	},
	{
		title: 'Playboy Specials',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'BM',
	},
	{
		title: 'Swank',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Variations',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: '30+ 40+ 50+',
		image: 'assets/images/xxx.jpg',
		genre: '13 - Adult Sophisticates',
		minorder: '3 (each)',
		frequency: 'M',
	},

// Ethnic
//	{
//		title: 'Ebony',
//		image: 'assets/images/ebony.jpg',
//		genre: '14 - Ethnic',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Essence',
		image: 'assets/images/essence.jpg',
		genre: '14 - Ethnic',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Jet',
//		image: 'assets/images/jet.jpg',
//		genre: '14 - Ethnic',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'People En Espanol',
		image: 'assets/images/people_en_espanol.jpg',
		genre: '14 - Ethnic',
		minorder: '2',
		frequency: 'M',
	},
//	{
//		title: 'Smooth',
//		image: 'assets/images/smooth.jpg',
//		genre: '14 - Ethnic',
//		minorder: '*',
//		frequency: '*',
//	},

// Cooking
	{
		title: 'Bon Appétit',
		image: 'assets/images/bon_appetit.jpg',
		genre: '15 - Cooking',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Cooking Light',
		image: 'assets/images/cooking_light.jpg',
		genre: '15 - Cooking',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Everyday Rachael Ray',
		image: 'assets/images/everyday_rachael_ray.jpg',
		genre: '15 - Cooking',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Food Network Magazine',
		image: 'assets/images/food_network_magazine.jpg',
		genre: '15 - Cooking',
		minorder: '3',
		frequency: 'M',
	},

// Home & Garden
	{
		title: 'Better Homes & Gardens',
		image: 'assets/images/better_homes_gardens.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Country Living',
		image: 'assets/images/country_living.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'HGTV Magazine',
		image: 'assets/images/hgtv_magazine.jpg',
		genre: '16 - Home & Garden',
		minorder: '3',
		frequency: 'BM',
	},
	{
		title: 'House Beautiful',
		image: 'assets/images/house_beautiful.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Martha Stewart Living',
		image: 'assets/images/martha_stewart_living.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Real Simple',
		image: 'assets/images/real_simple.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Southern Living',
		image: 'assets/images/southern_living.jpg',
		genre: '16 - Home & Garden',
		minorder: '2',
		frequency: 'M',
	},

// Miscellaneous
	{
		title: 'Combat Handguns',
		image: 'assets/images/combat_handguns.jpg',
		genre: '17 - Miscellaneous',
		minorder: '5',
		frequency: 'M',
	},
	{
		title: 'Family Handyman',
		image: 'assets/images/no-pic.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Guns & Ammo',
		image: 'assets/images/guns_ammo.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Guns & Weapons',
		image: 'assets/images/guns_weapons.jpg',
		genre: '17 - Miscellaneous',
		minorder: '5',
		frequency: 'M',
	},
	{
		title: 'High Times',
		image: 'assets/images/high_times.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Mad Magazine',
		image: 'assets/images/mad_magazine.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'BM',
	},
	{
		title: 'Old Farmers Almanac',
		image: 'assets/images/old_farmers_almanac.jpg',
		genre: '17 - Miscellaneous',
		minorder: '20',
		frequency: 'A',
	},
//	{
//		title: 'Parents',
//		image: 'assets/images/parents.jpg',
//		genre: '17 - Miscellaneous',
//		minorder: '*',
//		frequency: '*',
//	},
	{
		title: 'Popular Mechanics',
		image: 'assets/images/popular_mechanics.jpg',
		genre: '17 - Miscellaneous',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Popular Science',
		image: 'assets/images/popular_science.jpg',
		genre: '17 - Miscellaneous',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Psychology Today',
		image: 'assets/images/psychology_today.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Readers Digest',
		image: 'assets/images/readers_digest.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Skin & Ink',
		image: 'assets/images/skin_ink.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Tattoo',
		image: 'assets/images/tattoo.jpg',
		genre: '17 - Miscellaneous',
		minorder: '3',
		frequency: 'M',
	},
	{
		title: 'Tattoo Flash',
		image: 'assets/images/no-pic.jpg',
		genre: '17 - Miscellaneous',
		minorder: '2',
		frequency: 'M',
	},
	{
		title: 'Yankee',
		image: 'assets/images/yankee.jpg',
		genre: '17 - Miscellaneous',
		minorder: '10',
		frequency: 'BM',
	}
];